# Generated by Django 5.1.15 on 2026-04-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID — used for idempotency (reject duplicate webhooks)', max_length=100, null=True, unique=True),
        ),
    ]
