# Generated by Django 5.1.15 on 2026-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('RETRY', 'Retry'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
