# Generated by Django 5.1.15 on 2026-04-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(help_text='User ID associated with the failed event')),
                ('payload', models.JSONField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dead_letter_queue',
                'ordering': ['-created_at'],
            },
        ),
    ]
